import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import "@rainbow-me/rainbowkit/styles.css";
import Provider from "@/provider";
import { Toaster } from "sonner";
import NewNav from "@/components/NewNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="w-full mx-auto container ">
          <Provider>
            <div className="sm:px-12">
              {children}
            </div>
            <Toaster />
          </Provider>
        </div>
      </body>
    </html>
  );
}
